import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    headerLogo: {
      backgroundColor: "#0D0D0D",
      height: 173,
      alignItems: "center",
      justifyContent: "center",
      padding: 10,
    },
    container: {
      flex: 1,
      backgroundColor: "#1A1A1A",
      justifyContent: "flex-start",
    },
    wrapInput: {
      top: -27,
      alignItems: "flex-start",
      justifyContent: "center",
      height: 52,
      flexDirection: "row",
      paddingLeft: 24,
      paddingRight: 24,
    },
    input: {
      flex: 1,
      backgroundColor: "#262626",
      width: "100%",
      height: 54,
      borderRadius: 5,
      color: "#F2F2F2",
      fontSize: 16,
      padding: 10,
      marginBottom: 0,
      borderWidth: 1,
      borderColor: "#000",
      borderStyle: "solid",
      marginRight: 4,
    },
    inputFocused: {
        flex: 1,
        backgroundColor: "#262626",
        width: "100%",
        height: 54,
        borderRadius: 5,
        color: "#F2F2F2",
        fontSize: 16,
        padding: 10,
        marginBottom: 0,
        borderWidth: 1,
        borderColor: "#5E60CE",
        borderStyle: "solid",
        marginRight: 4,
    },
    buttonAdd: {
      width: 52,
      height: 52,
      backgroundColor: "#1E6F9F",
      justifyContent: "center",
      alignItems: "center",
      borderRadius: 6,
      bottom: 52,
    },
    buttonBehind: {
      width: 52,
      height: 52,
      backgroundColor: "#fff",
      justifyContent: "center",
      alignItems: "center",
      borderRadius: 6,
      top: 0,
    },
    followUpActions: {
      flexDirection: "row",
      height: 19,
      top: 12,
      justifyContent: "space-between",
      alignItems: "flex-start",
      paddingLeft: 24,
      paddingRight: 24,
      marginBottom: 30,
    },
    wrapCreatedTasks: {
      flexDirection: "row",
      justifyContent: "flex-start",
    },
    createdTasksTexts: {
      color: "#4EA8DE",
      paddingRight: 8,
      fontSize: 14,
      fontWeight: "800",
      justifyContent: "center",
    },
    wrapNumberTasksCreated: {
      backgroundColor: "#333333",
      width: 25,
      height: 19,
      borderRadius: 30,
      alignItems: "center",
      justifyContent: "center",
    },
    numberTasksCreated: {
      color: "#fff",
      fontSize: 12,
      fontWeight: "800",
    },
    wrapCompletedTasks: {
      flexDirection: "row",
    },
    completedTasksTexts: {
      color: "#8284FA",
      paddingRight: 8,
      fontSize: 14,
      fontWeight: "800",
      justifyContent: "center",
    },
    wrapNumberTasksCompleted: {
      backgroundColor: "#333333",
      width: 25,
      height: 19,
      borderRadius: 30,
      alignItems: "center",
      justifyContent: "center",
    },
    numberTasksCompleted: {
      color: "#fff",
      fontSize: 12,
      fontWeight: "800",
    },
  });
  